#! /usr/bin/env python
# -*- coding: utf-8 -*-

from pvaccess import *
import random

# ========== From the pvaPy doc, written by Sinisa Veseli ==========
def createNTTable(pvRequest):
	
	nRows = pvRequest.getInt('nRows')
	
	nCols = pvRequest.getInt('nCols')

	ntTable = NtTable(nCols, DOUBLE)

	labels = []

	for j in range(0, nCols):
		
		labels.append('Column%s' % j)

		column = []

		for i in range(0, nRows):

			column.append(random.uniform(0, 1))

		ntTable.setColumn(j, column)

	ntTable.setLabels(labels)

	ntTable.setDescriptor('Automatically generated by pvaPy RPC server')

	return ntTable
# ==================================================================

rpcServer = RpcServer()

rpcServer.registerService('createNTTable', createNTTable)

rpcServer.startListener()

while True:
	usr_input = raw_input("type 'exit' to quit: ")
	if usr_input == 'exit':
		rpcServer.stopListener()
		break
